---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: test
---
kind: ResourceLocker
metadata:
  name: test-patch
spec:
  patches:
    - patchTemplate: |-
        spec:
          ports:
            - protocol: TCP
      patchType: application/strategic-merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Service
        namespace: test
        name: test
    - patchTemplate: |-
        spec: {}
      patchType: application/strategic-merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Endpoints
        namespace: test
        name: test
---
kind: ResourceLocker
metadata:
  name: test2
spec:
  resources: []
