parameters:
  kapitan:
    compile:
      - input_paths:
          - adhoc-configurations/component/app.jsonnet
        input_type: jsonnet
        output_path: apps/
      - input_paths:
          - inventory/classes/${cluster:tenant}/${adhoc_configurations:manifests_path}/${cluster:name}
        input_type: copy
        output_path: adhoc-configurations/
