parameters:
  kapitan:
    compile:
      - input_paths:
          - ${_base_directory}/component/app.jsonnet
        input_type: jsonnet
        output_path: .
      - input_paths:
          - inventory/classes/${cluster:tenant}/${adhoc_configurations:manifests_path}
        input_type: copy
        output_path: ${_instance}
      - input_paths:
          - ${_base_directory}/component/main.jsonnet
        input_type: jsonnet
        output_path: ${_instance}
  commodore:
    postprocess:
      filters:
        - type: jsonnet
          path: ${_instance}
          filter: postprocess/patch_operator.jsonnet
