parameters:
  kapitan:
    compile:
      - input_paths:
          - adhoc-configurations/component/app.jsonnet
        input_type: jsonnet
        output_path: apps/
      - input_paths:
          - adhoc-configurations/component/main.jsonnet
        input_type: jsonnet
        output_path: adhoc-configurations/

